name: Deploy AWS CloudFormation Stack

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Validate CloudFormation Template
      run: aws cloudformation validate-template --template-body file://cf_template.yaml

    - name: Deploy CloudFormation Stack
      run: aws cloudformation deploy --stack-name my-stack --template-file cf_template.yaml --capabilities CAPABILITY_NAMED_IAM
